version: '3'

services:
  api-service:
    image: node:16-alpine
    container_name: api_server
    working_dir: /app
    volumes:
      - ./api/api:/api
      - ./api/package.json:/package.json
      - ./api/tsconfig.json:/tsconfig.json
    ports:
      - '3001:3001'
    command : sh -c "yarn install && yarn start-api-dev"
    env_file : 
      - server/.env

  realtime-service:
    image: node:16-alpine
    container_name: realtime_server
    working_dir: /real
    volumes:
      - .server/realtime:/realtime
      - .server/package.json:/package.json
      - ./server/tsconfig.json:/tsconfig.json
    ports:
      - '3002:3002'
    command: sh -c "yarn install && yarn start-realtime-dev"
    env_file:
      - server/.env

  client-service:
    image: node:16-alpine
    container_name: client_server
    working_dir : /app
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    command : sh -c "yarn install && npm run dev"
    env_file: 
      - client/.env.local